version: 2.1

jobs:
  build:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cimg/base:2022.03 # the primary container, where your job's commands are run
    steps:
      - checkout
      - run: echo "hello world" # run the `echo` command

workflows:
  build-workflow:
    jobs:
      - build